jobs:

- job: logo
  displayName: Print Logo
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - script: echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.raw)"

- job: test
  displayName: Test
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: "**/*.Test.csproj"
      arguments: --configuration Release

- job: e2eLint
  displayName: E2E lint
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - bash: |
      cd ./test/e2e
      yarn
      yarn lint

- job: e2eInMemoryEventStore
  displayName: E2E in-memory event store
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - bash: |
      docker-compose -f ./docker-compose.app-in-memory.yml up --detach
      cd ./test/e2e
      yarn
      yarn test

- job: e2eSqlEventStore
  displayName: E2E SQL event store
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - bash: |
      docker-compose -f ./docker-compose.app-sql.yml up --detach
      cd ./test/e2e
      yarn
      yarn test
