jobs:

- job: logo
  displayName: Print Logo
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - script: echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.raw)"

- job: build
  displayName: Build Solutions
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - bash: dotnet build 0.All.sln --configuration Release
    displayName: Build 0.All.sln
  - bash: dotnet build 1.InMemoryEventStore.InMemoryReadModel.sln --configuration Release
    displayName: Build 1.InMemoryEventStore.InMemoryReadModel.sln
  - bash: dotnet build 2.SqlEventStore.InMemoryReadModel.sln --configuration Release
    displayName: Build 2.SqlEventStore.InMemoryReadModel.sln
  - bash: dotnet build 3.NoSqlEventStore.InMemoryReadModel.sln --configuration Release
    displayName: Build 3.NoSqlEventStore.InMemoryReadModel.sln

- job: test
  displayName: Test
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: "**/*.Test.csproj"
      arguments: --configuration Release

- job: e2eLint
  displayName: E2E Lint
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - bash: |
      cd ./test/e2e
      yarn
      yarn lint
    displayName: Run lint

- job: e2eInMemoryEventStore
  displayName: E2E In-Memory Event Store
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - bash: |
      docker-compose -f ./docker-compose.1.in-memory-event-store.in-memory-readmodel.yml up --detach
      cd ./test/e2e
      yarn
      yarn test
    displayName: Run e2e tests

- job: e2eSqlEventStore
  displayName: E2E SQL Event Store
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - bash: |
      docker-compose -f ./docker-compose.2.sql-event-store.in-memory-readmodel.yml up --detach
      cd ./test/e2e
      yarn
      yarn test
    displayName: Run e2e tests

- job: e2eNoSqlEventStore
  displayName: E2E NoSQL Event Store
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - bash: |
      docker-compose -f ./docker-compose.3.nosql-event-store.in-memory-readmodel.yml up --detach
      cd ./test/e2e
      yarn
      yarn test
    displayName: Run e2e tests
