pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.raw)"
  displayName: "Print logo"

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*.Test.csproj'
    arguments: "--configuration Release"

- script: docker-compose build
  displayName: "Build Docker image"
