version: "3"

services:

  todo:
    build:
      context: ./src
      dockerfile: Dockerfile.no-sql
    ports:
      - "8080:80"
    environment:
      DB_USER: root
      DB_PASSWORD: secret
    depends_on:
      - no-sql
    restart: on-failure

  no-sql:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  no-sql-web:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: no-sql
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
