version: "3"

services:

  todo:
    build:
      context: ./src
      dockerfile: Dockerfile.2.sql-event-store.in-memory-readmodel
    ports:
      - "8080:80"
    environment:
      EVENT_STORE_HOST: event-store
      EVENT_STORE_USER: root
      EVENT_STORE_PASSWORD: secret
    depends_on:
      - event-store
    restart: on-failure

  event-store:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret

  event-store-ui:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - event-store
    restart: on-failure
