FROM microsoft/dotnet:2.2-sdk AS build-env
WORKDIR /app
COPY . ./
RUN dotnet publish -c Release -o out ./apps/1.in-memory-event-store.in-memory-readmodel/frontend/Frontend.csproj

FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/apps/1.in-memory-event-store.in-memory-readmodel/frontend/out .
ENTRYPOINT ["dotnet", "Frontend.dll"]
