FROM microsoft/dotnet:2.2-sdk AS build-env
WORKDIR /app
COPY . ./
RUN dotnet publish -c Release -o out ./apps/5.distributed.no-sql-event-store.no-sql-readmodel/writes/Writes.csproj

FROM microsoft/2.2-aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/apps/5.distributed.no-sql-event-store.no-sql-readmodel/writes/out .
ENTRYPOINT ["dotnet", "Writes.dll"]
