FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build-env
WORKDIR /app
COPY . ./
RUN dotnet publish -c Release -o out ./apps/5.distributed.no-sql-event-store.no-sql-readmodel/frontend/Frontend.csproj

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0
WORKDIR /app
COPY --from=build-env /app/apps/5.distributed.no-sql-event-store.no-sql-readmodel/frontend/out .
ENTRYPOINT ["dotnet", "Frontend.dll"]
