FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build-env
WORKDIR /app
COPY . ./
RUN dotnet publish -c Release -o out ./apps/2.sql-event-store.in-memory-readmodel/frontend/Frontend.csproj

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Frontend.dll"]
