FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app
COPY . ./
RUN dotnet publish -c Release -o out ./apps/3.no-sql-event-store.in-memory-readmodel/frontend/Frontend.csproj

FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/apps/3.no-sql-event-store.in-memory-readmodel/frontend/out .
ENTRYPOINT ["dotnet", "Frontend.dll"]
