FROM microsoft/dotnet:2.2-sdk AS build-env
WORKDIR /app
COPY . ./
RUN dotnet publish -c Release -o out ./apps/4.no-sql-event-store.no-sql-readmodel/frontend/Frontend.csproj

FROM microsoft/2.2-aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/apps/4.no-sql-event-store.no-sql-readmodel/frontend/out .
ENTRYPOINT ["dotnet", "Frontend.dll"]
